"""Sink-group pattern/exclude/custom-key management handlers."""

from __future__ import annotations

import argparse
from typing import Any, cast

from cdc_generator.cli.sink_group_common import (
    get_sink_file_path,
    resolve_sink_group_for_pattern_update,
)
from cdc_generator.core.sink_types import SinkGroupConfig
from cdc_generator.helpers.helpers_logging import (
    print_error,
    print_header,
    print_info,
    print_success,
    print_warning,
)
from cdc_generator.helpers.helpers_sink_groups import (
    load_sink_groups,
    save_sink_groups,
)


def handle_remove_sink_group_command(args: argparse.Namespace) -> int:
    """Remove a sink group."""
    sink_file = get_sink_file_path()

    if not args.remove:
        print_error("Sink group name required")
        return 1

    try:
        sink_groups = load_sink_groups(sink_file)
    except FileNotFoundError:
        print_error(f"Sink groups file not found: {sink_file}")
        return 1

    if not sink_groups:
        print_warning("sink-groups.yaml is empty — no sink groups to remove")
        return 1

    sink_group_name = args.remove

    if sink_group_name not in sink_groups:
        print_error(f"Sink group '{sink_group_name}' not found")
        print_info(f"Available sink groups: {list(sink_groups.keys())}")
        return 1

    # Inherited sink groups are auto-generated — cannot be removed directly
    sink_group = sink_groups[sink_group_name]
    if sink_group.get("inherits", False):
        source_name = sink_group_name.removeprefix("sink_")
        print_error(
            f"Cannot remove '{sink_group_name}' — it inherits from"
            + f" source group '{source_name}'"
        )
        print_info(
            "Inherited sink groups are auto-generated by --create."
            + " Remove the source group instead, or recreate without it."
        )
        return 1

    # Confirm removal
    print_warning(f"This will remove sink group '{sink_group_name}'")

    del sink_groups[sink_group_name]
    save_sink_groups(sink_groups, sink_file)

    print_success(f"Removed sink group '{sink_group_name}'")

    return 0


def handle_add_source_custom_key_command(args: argparse.Namespace) -> int:
    """Add or update SQL-based source custom key for a sink group."""
    key_name = str(args.add_source_custom_key or "").strip()
    key_value = str(args.custom_key_value or "").strip()
    exec_type = str(args.custom_key_exec_type or "sql").strip().lower()

    if not key_name:
        print_error("--add-source-custom-key requires a key name")
        return 1
    if not key_value:
        print_error("--custom-key-value is required with --add-source-custom-key")
        return 1
    if exec_type != "sql":
        print_error("Only --custom-key-exec-type sql is supported")
        return 1

    result = resolve_sink_group_for_pattern_update(
        args,
        action_flag="--add-source-custom-key",
    )
    if isinstance(result, int):
        return result

    sink_groups, sink_group_name, sink_group, sink_file = result
    sink_group_map = cast(dict[str, Any], sink_group)

    source_custom_keys_raw = sink_group_map.get("source_custom_keys")
    source_custom_keys: dict[str, dict[str, str]] = {}
    if isinstance(source_custom_keys_raw, dict):
        for existing_key_raw, existing_value_raw in cast(dict[str, object], source_custom_keys_raw).items():
            existing_key = str(existing_key_raw).strip()
            if not existing_key:
                continue
            if isinstance(existing_value_raw, dict):
                value_dict = cast(dict[str, object], existing_value_raw)
                existing_exec = str(value_dict.get("exec_type", "sql")).strip().lower() or "sql"
                existing_value = str(value_dict.get("value", "")).strip()
                if existing_value:
                    source_custom_keys[existing_key] = {
                        "exec_type": existing_exec,
                        "value": existing_value,
                    }
            elif isinstance(existing_value_raw, str):
                existing_value = existing_value_raw.strip()
                if existing_value:
                    source_custom_keys[existing_key] = {
                        "exec_type": "sql",
                        "value": existing_value,
                    }

    source_custom_keys[key_name] = {
        "exec_type": exec_type,
        "value": key_value,
    }
    sink_group_map["source_custom_keys"] = source_custom_keys
    sink_groups[sink_group_name] = cast(SinkGroupConfig, sink_group_map)
    save_sink_groups(sink_groups, sink_file)

    print_success(
        f"Saved source custom key '{key_name}' for sink group '{sink_group_name}'"
    )
    return 0


def _parse_csv_patterns(raw_value: str) -> list[str]:
    """Parse comma-separated pattern input and return cleaned entries."""
    return [
        item.strip()
        for item in raw_value.split(",")
        if item.strip()
    ]


def _append_unique_patterns(
    existing_values: object,
    incoming_values: list[str],
) -> tuple[list[str], int]:
    """Append unique string patterns preserving order.

    Returns the merged list and number of newly added patterns.
    """
    merged: list[str] = []
    if isinstance(existing_values, list):
        for item in cast(list[object], existing_values):
            value = str(item).strip()
            if value and value not in merged:
                merged.append(value)

    added_count = 0
    for value in incoming_values:
        if value not in merged:
            merged.append(value)
            added_count += 1

    return merged, added_count


def handle_add_to_ignore_list_command(args: argparse.Namespace) -> int:
    """Add database exclude pattern(s) to sink group configuration."""
    if not args.add_to_ignore_list:
        print_error("--add-to-ignore-list requires a pattern")
        return 1

    parsed_patterns = _parse_csv_patterns(str(args.add_to_ignore_list))
    if not parsed_patterns:
        print_error("No valid patterns provided for --add-to-ignore-list")
        return 1

    result = resolve_sink_group_for_pattern_update(
        args,
        action_flag="--add-to-ignore-list",
    )
    if isinstance(result, int):
        return result

    sink_groups, sink_group_name, sink_group, sink_file = result
    merged_patterns, added_count = _append_unique_patterns(
        sink_group.get("database_exclude_patterns", []),
        parsed_patterns,
    )
    cast(dict[str, Any], sink_group)["database_exclude_patterns"] = merged_patterns
    sink_groups[sink_group_name] = sink_group
    save_sink_groups(sink_groups, sink_file)

    print_success(
        f"Updated database_exclude_patterns for sink group '{sink_group_name}'"
    )
    print_info(
        f"Patterns: +{added_count} added"
        + f" (total: {len(merged_patterns)})"
    )
    return 0


def handle_add_to_schema_excludes_command(args: argparse.Namespace) -> int:
    """Add schema exclude pattern(s) to sink group configuration."""
    if not args.add_to_schema_excludes:
        print_error("--add-to-schema-excludes requires a pattern")
        return 1

    parsed_patterns = _parse_csv_patterns(str(args.add_to_schema_excludes))
    if not parsed_patterns:
        print_error("No valid patterns provided for --add-to-schema-excludes")
        return 1

    result = resolve_sink_group_for_pattern_update(
        args,
        action_flag="--add-to-schema-excludes",
    )
    if isinstance(result, int):
        return result

    sink_groups, sink_group_name, sink_group, sink_file = result
    merged_patterns, added_count = _append_unique_patterns(
        sink_group.get("schema_exclude_patterns", []),
        parsed_patterns,
    )
    cast(dict[str, Any], sink_group)["schema_exclude_patterns"] = merged_patterns
    sink_groups[sink_group_name] = sink_group
    save_sink_groups(sink_groups, sink_file)

    print_success(
        f"Updated schema_exclude_patterns for sink group '{sink_group_name}'"
    )
    print_info(
        f"Patterns: +{added_count} added"
        + f" (total: {len(merged_patterns)})"
    )
    return 0


def handle_add_to_table_excludes_command(args: argparse.Namespace) -> int:
    """Add table exclude pattern(s) to sink group configuration."""
    if not args.add_to_table_excludes:
        print_error("--add-to-table-excludes requires a pattern")
        return 1

    parsed_patterns = _parse_csv_patterns(str(args.add_to_table_excludes))
    if not parsed_patterns:
        print_error("No valid patterns provided for --add-to-table-excludes")
        return 1

    result = resolve_sink_group_for_pattern_update(
        args,
        action_flag="--add-to-table-excludes",
    )
    if isinstance(result, int):
        return result

    sink_groups, sink_group_name, sink_group, sink_file = result
    merged_patterns, added_count = _append_unique_patterns(
        sink_group.get("table_exclude_patterns", []),
        parsed_patterns,
    )
    cast(dict[str, Any], sink_group)["table_exclude_patterns"] = merged_patterns
    sink_groups[sink_group_name] = sink_group
    save_sink_groups(sink_groups, sink_file)

    print_success(
        f"Updated table_exclude_patterns for sink group '{sink_group_name}'"
    )
    print_info(
        f"Patterns: +{added_count} added"
        + f" (total: {len(merged_patterns)})"
    )
    return 0


def handle_list_table_excludes_command(args: argparse.Namespace) -> int:
    """List table exclude patterns from sink group configuration."""
    result = resolve_sink_group_for_pattern_update(
        args,
        action_flag="--list-table-excludes",
    )
    if isinstance(result, int):
        return result

    _sink_groups, sink_group_name, sink_group, _sink_file = result
    patterns = sink_group.get("table_exclude_patterns", [])
    patterns_list = patterns if isinstance(patterns, list) else []

    print_header(f"Table Exclude Patterns: {sink_group_name}")
    if not patterns_list:
        print_info("No table exclude patterns configured")
        return 0

    for item in patterns_list:
        print_info(f"  • {item}")
    return 0
