"""File writing utilities for migration generation.

Contains functions for writing SQL files with checksums and manifests.
"""

from __future__ import annotations

import hashlib
from pathlib import Path
from typing import Any

from .data_structures import GenerationResult, SinkTarget
from .helpers import DO_NOT_EDIT_HEADER


def _compute_checksum(content: str) -> str:
    """Compute SHA256 checksum of SQL content, excluding the header block.

    Strips the auto-generated header (everything up to and including the
    closing ``-- ====...`` separator) so that timestamp-only changes do
    not alter the checksum.

    Args:
        content: SQL file content.

    Returns:
        Hex digest string.
    """
    header_end = "-- " + "=" * 76
    first_sep = content.find(header_end)
    if first_sep != -1:
        second_sep = content.find(header_end, first_sep + len(header_end))
        if second_sep != -1:
            # Strip everything up to (and including) the closing separator line
            line_end = content.index("\n", second_sep)
            body = content[line_end + 1:]
        else:
            line_end = content.index("\n", first_sep)
            body = content[line_end + 1:]
    else:
        body = content
    return hashlib.sha256(body.encode("utf-8")).hexdigest()


def _inject_checksum(content: str) -> str:
    """Inject a SHA256 checksum comment after the header block.

    The checksum is computed from the content *without* the checksum line
    and *without* the header block (timestamps), making it possible to
    verify whether the SQL body was manually edited.

    Args:
        content: SQL file content.

    Returns:
        Content with checksum line inserted after the header separator.
    """
    checksum = _compute_checksum(content)
    checksum_line = f"-- Checksum: sha256:{checksum}"

    # Insert after the closing header separator (second ===... line)
    header_end = "-- " + "=" * 76
    first_sep = content.find(header_end)
    if first_sep == -1:
        # No header block — prepend
        return checksum_line + "\n" + content

    # Find the second separator (closing line of the header block)
    second_sep = content.find(header_end, first_sep + len(header_end))
    if second_sep == -1:
        # Only one separator — insert after it
        line_end = content.index("\n", first_sep)
        return content[:line_end + 1] + checksum_line + "\n" + content[line_end + 1:]

    # Insert after the closing separator
    line_end = content.index("\n", second_sep)
    return content[:line_end + 1] + checksum_line + "\n" + content[line_end + 1:]


def _normalize_sql_for_compare(content: str) -> str:
    """Normalize generated SQL for change detection.

    Removes volatile header lines that change every generation run even when
    SQL logic is unchanged.

    Args:
        content: SQL content.

    Returns:
        Stable normalized string for equality comparison.
    """
    stable_lines: list[str] = []
    for line in content.splitlines():
        if line.startswith("-- Generated: "):
            continue
        if line.startswith("-- Checksum: sha256:"):
            continue
        stable_lines.append(line)
    return "\n".join(stable_lines).strip()


def _write_migration_file(
    output_path: Path,
    content: str,
    result: GenerationResult,
) -> None:
    """Write a migration SQL file with checksum, creating dirs as needed.

    Injects a SHA256 checksum comment after the header block for
    tamper detection during ``cdc manage-migrations apply``.

    Args:
        output_path: Target file path.
        content: SQL content to write.
        result: GenerationResult to update.
    """
    final = _inject_checksum(content)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    result.files_written += 1

    if output_path.exists():
        existing = output_path.read_text(encoding="utf-8")
        if _normalize_sql_for_compare(existing) == _normalize_sql_for_compare(final):
            return

    output_path.write_text(final, encoding="utf-8")


def write_migration_file(
    output_path: Path,
    content: str,
    result: GenerationResult,
) -> None:
    """Public wrapper around migration SQL file writing."""
    _write_migration_file(output_path, content, result)


def _write_manifest(
    output_dir: Path,
    tables: list[str],
    schemas: list[str],
    generated_at: str,
    sink_target: SinkTarget,
) -> bool:
    """Write manifest.yaml listing all generated migration files.

    Args:
        output_dir: Migration output directory.
        tables: List of table names.
        schemas: List of schema names.
        generated_at: Timestamp string.
        sink_target: Resolved sink target info.
    """
    manifest_lines = [
        "# DO NOT EDIT — AUTO-GENERATED by: cdc manage-migrations generate",
        f"generated_at: \"{generated_at}\"",
        f"table_count: {len(tables)}",
        f"schema_count: {len(schemas)}",
        "sink_target:",
        f"  name: \"{sink_target.sink_name}\"",
        f"  sink_group: \"{sink_target.sink_group}\"",
        f"  service: \"{sink_target.sink_service}\"",
        "  databases:",
    ]
    for env_name in sorted(sink_target.databases):
        db_name = sink_target.databases[env_name]
        manifest_lines.append(f"    {env_name}: \"{db_name}\"")
    manifest_lines.extend([
        "infrastructure:",
        "  - 00-infrastructure/01-create-schemas.sql",
        "  - 00-infrastructure/02-cdc-management.sql",
        "tables:",
    ])
    for table in sorted(tables):
        manifest_lines.append(f"  - 01-tables/{table}.sql")
        manifest_lines.append(f"  - 01-tables/{table}-staging.sql")
    manifest_lines.append("schemas:")
    for schema in sorted(schemas):
        manifest_lines.append(f"  - {schema}")
    manifest_lines.append("")

    manifest_path = output_dir / "manifest.yaml"
    final = "\n".join(manifest_lines)

    if manifest_path.exists():
        existing = manifest_path.read_text(encoding="utf-8")
        existing_stable = "\n".join(
            line for line in existing.splitlines()
            if not line.startswith("generated_at:")
        ).strip()
        final_stable = "\n".join(
            line for line in final.splitlines()
            if not line.startswith("generated_at:")
        ).strip()
        if existing_stable == final_stable:
            return False

    manifest_path.write_text(final, encoding="utf-8")
    return True


def write_manifest(
    output_dir: Path,
    tables: list[str],
    schemas: list[str],
    generated_at: str,
    sink_target: SinkTarget,
) -> bool:
    """Public wrapper around manifest writing."""
    return _write_manifest(output_dir, tables, schemas, generated_at, sink_target)