"""Helper functions for migration generation.

Contains utility functions for loading, building columns, etc.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, cast

from jinja2 import Environment, FileSystemLoader

from cdc_generator.core.column_template_operations import (
    resolve_column_templates,
    resolve_transforms,
)
from cdc_generator.helpers.service_schema_paths import get_service_schema_read_dirs
from cdc_generator.helpers.type_mapper import TypeMapper
from cdc_generator.helpers.yaml_loader import load_yaml_file

from .data_structures import MigrationColumn


TEMPLATES_DIR = Path(__file__).parent.parent.parent / "templates" / "migrations"
DO_NOT_EDIT_HEADER = "-- DO NOT EDIT — AUTO-GENERATED by: cdc manage-migrations generate"


def _create_jinja_env() -> Environment:
    """Create Jinja2 environment with custom filters.

    Returns:
        Configured Jinja2 Environment.
    """
    env = Environment(
        loader=FileSystemLoader(str(TEMPLATES_DIR)),
        keep_trailing_newline=True,
        trim_blocks=True,
        lstrip_blocks=True,
    )
    env.filters["format_pk"] = lambda name: f'"{name}"'
    return env


def load_table_definitions(
    service_name: str,
    project_root: Path,
) -> dict[str, dict[str, Any]]:
    """Load table definitions from services/_schemas/{service}/{schema}/{table}.yaml.

    Searches all source schema subdirectories (e.g., dbo/) and loads each
    YAML file as a table definition. The key is '{schema}.{table}' matching
    the source reference format (e.g., 'dbo.Actor').

    Args:
        service_name: Service name (e.g., 'adopus').
        project_root: Implementation project root.

    Returns:
        Dict mapping 'schema.table' to table definition dict.
    """
    schema_dirs = get_service_schema_read_dirs(service_name, project_root)

    tables: dict[str, dict[str, Any]] = {}
    for schema_dir in schema_dirs:
        if not schema_dir.exists():
            continue
        # Each subdirectory is a source schema (e.g., dbo/)
        for sub_dir in sorted(schema_dir.iterdir()):
            if not sub_dir.is_dir():
                continue
            schema_name = sub_dir.name
            for yaml_file in sorted(sub_dir.glob("*.yaml")):
                raw_dict = cast(dict[str, Any], load_yaml_file(yaml_file))
                table_name = raw_dict.get("table")
                if not isinstance(table_name, str):
                    # Fallback: derive from filename
                    table_name = yaml_file.stem
                key = f"{schema_name}.{table_name}"
                if key not in tables:
                    tables[key] = raw_dict
    return tables


def _load_source_groups(project_root: Path) -> dict[str, Any]:
    """Load source-groups.yaml from the project root.

    Args:
        project_root: Implementation project root.

    Returns:
        Parsed source groups dict.
    """
    sg_path = project_root / "source-groups.yaml"
    if not sg_path.exists():
        return {}
    raw = load_yaml_file(sg_path)
    return cast(dict[str, Any], raw)


def build_columns_from_table_def(
    table_def: dict[str, Any],
    ignore_columns: list[str] | None = None,
    type_mapper: TypeMapper | None = None,
) -> tuple[list[MigrationColumn], list[str]]:
    """Build column list from a service-schema YAML.

    Supports both formats:
    - services/_schemas format: ``columns[].name``, ``columns[].type`` (MSSQL types)
    - generated/table-definitions format: ``fields[].postgres``, ``fields[].type`` (PG types)

    When reading MSSQL types from _schemas, uses TypeMapper to convert to PG types.

    Args:
        table_def: Parsed table definition dict.
        ignore_columns: Column names to exclude.
        type_mapper: Optional type mapper for MSSQL→PG conversion.

    Returns:
        Tuple of (columns, primary_keys).
    """
    ignore_set = {c.casefold() for c in (ignore_columns or [])}

    # Detect format: _schemas uses 'columns', table-definitions uses 'fields'
    columns_raw = table_def.get("columns", table_def.get("fields", []))
    if not isinstance(columns_raw, list):
        return [], []

    # Detect which format we're reading:
    # _schemas format has 'columns' key and MSSQL types
    is_schemas_format = "columns" in table_def

    columns: list[MigrationColumn] = []
    primary_keys: list[str] = []
    seen_column_names: set[str] = set()

    for field_entry in cast(list[object], columns_raw):
        if not isinstance(field_entry, dict):
            continue
        f = cast(dict[str, Any], field_entry)

        # Column name: _schemas uses 'name', table-definitions may use 'postgres'
        pg_name = str(f.get("name", f.get("postgres", "")))
        if not pg_name:
            continue
        if pg_name.casefold() in ignore_set:
            continue
        column_key = pg_name.casefold()
        if column_key in seen_column_names:
            continue
        seen_column_names.add(column_key)

        # Type: _schemas has MSSQL types that need mapping, table-defs have PG types
        raw_type = str(f.get("type", "TEXT"))
        pg_type = (
            type_mapper.map_type(raw_type)
            if is_schemas_format and type_mapper is not None
            else raw_type
        )

        col = MigrationColumn(
            name=pg_name,
            type=pg_type,
            nullable=bool(f.get("nullable", True)),
            primary_key=bool(f.get("primary_key", False)),
        )
        columns.append(col)
        if col.primary_key:
            primary_keys.append(pg_name)

    return columns, _dedupe_names_case_insensitive(primary_keys)


def _add_column_template_columns(
    columns: list[MigrationColumn],
    table_cfg: dict[str, object],
) -> list[MigrationColumn]:
    """Add columns from column_templates to the column list.

    Args:
        columns: Existing column list.
        table_cfg: Sink table config with column_templates.

    Returns:
        Extended column list with template columns appended.
    """
    resolved = resolve_column_templates(table_cfg)
    existing_names = {c.name for c in columns}

    for r in resolved:
        if r.name in existing_names:
            continue
        col = MigrationColumn(
            name=r.name,
            type=r.template.column_type.upper(),
            nullable=not r.template.not_null,
            default=r.template.default,
        )
        columns.append(col)

    return columns


def _add_transform_output_columns(
    columns: list[MigrationColumn],
    table_cfg: dict[str, object],
) -> list[MigrationColumn]:
    """Add columns produced by transforms without altering configured names.

    For migration DDL, transform outputs are represented as nullable TEXT
    columns unless already present from source/table templates.

    Args:
        columns: Existing column list.
        table_cfg: Sink table config with transforms.
    """
    resolved = resolve_transforms(table_cfg)
    existing_names = {c.name for c in columns}

    for r in resolved:
        if r.output_column in existing_names:
            continue
        col = MigrationColumn(
            name=r.output_column,
            type="TEXT",
            nullable=True,
        )
        columns.append(col)

    return columns


def _add_cdc_metadata_columns(
    columns: list[MigrationColumn],
) -> list[MigrationColumn]:
    """Add CDC metadata columns to every table.

    These columns track sync state and operation metadata.

    Args:
        columns: Existing column list.

    Returns:
        Extended column list with CDC columns appended.
    """
    existing_names = {c.name for c in columns}

    for meta in CDC_METADATA_COLUMNS:
        name = meta["name"]
        if name in existing_names:
            continue
        col = MigrationColumn(
            name=name,
            type=meta["type"],
            nullable=meta["nullable"],
        )
        columns.append(col)

    return columns


def build_full_column_list(
    table_def: dict[str, Any],
    table_cfg: dict[str, object],
    ignore_columns: list[str] | None = None,
    type_mapper: TypeMapper | None = None,
) -> tuple[list[MigrationColumn], list[str]]:
    """Build complete column list including templates, transforms, and CDC metadata.

    Args:
        table_def: Parsed table definition dict.
        table_cfg: Sink table config.
        ignore_columns: Column names to exclude.
        type_mapper: Optional type mapper.

    Returns:
        Tuple of (full_columns, primary_keys).
    """
    columns, primary_keys = build_columns_from_table_def(
        table_def, ignore_columns, type_mapper,
    )

    columns = _add_column_template_columns(columns, table_cfg)
    columns = _add_transform_output_columns(columns, table_cfg)
    columns = _add_cdc_metadata_columns(columns)

    return columns, primary_keys


def _dedupe_names_case_insensitive(names: list[str]) -> list[str]:
    """Remove duplicate names case-insensitively, preserving original casing.

    Args:
        names: List of names.

    Returns:
        Deduped list preserving first occurrence's casing.
    """
    seen: set[str] = set()
    result: list[str] = []
    for name in names:
        key = name.casefold()
        if key not in seen:
            seen.add(key)
            result.append(name)
    return result


def _normalize_type_for_compare(type_name: str) -> str:
    """Normalize PostgreSQL type names for comparison.

    Strips size specs, normalizes aliases, etc.

    Args:
        type_name: Raw type name.

    Returns:
        Normalized type string.
    """
    normalized = type_name.strip().lower()
    if normalized.startswith("character varying"):
        normalized = "varchar"
    if normalized == "double precision":
        normalized = "float8"
    if normalized == "timestamp without time zone":
        normalized = "timestamp"
    if normalized == "timestamp with time zone":
        normalized = "timestamptz"
    return normalized


def _extract_manual_migration_hints(table_cfg: dict[str, Any]) -> ManualMigrationHints:
    """Extract optional manual migration hints from sink table config.

    Supported shape under sinks.<sink>.tables.<table>.manual_migration_hints:
      renames:
        - from: old_col
          to: new_col
      type_changes:
        - column: score
          using: "NULLIF(trim(\"score\"), '')::integer"
      set_not_null:
        - column: country
          pre_sql: "..."

    Args:
        table_cfg: Sink table config.

    Returns:
        Parsed hints.
    """
    hints_raw = table_cfg.get("manual_migration_hints")
    if not isinstance(hints_raw, dict):
        return ManualMigrationHints()

    hints = cast(dict[str, Any], hints_raw)
    parsed = ManualMigrationHints()

    renames_raw = hints.get("renames")
    if isinstance(renames_raw, list):
        for item in cast(list[Any], renames_raw):
            if not isinstance(item, dict):
                continue
            from_name = str(cast(dict[str, Any], item).get("from", "")).strip()
            to_name = str(cast(dict[str, Any], item).get("to", "")).strip()
            if from_name and to_name:
                parsed.renames.append((from_name, to_name))

    type_changes_raw = hints.get("type_changes")
    if isinstance(type_changes_raw, list):
        for item in cast(list[Any], type_changes_raw):
            if not isinstance(item, dict):
                continue
            change = cast(dict[str, Any], item)
            column_name = str(change.get("column", "")).strip()
            using_expr = str(change.get("using", "")).strip()
            if column_name and using_expr:
                parsed.type_casts[column_name.casefold()] = using_expr

    set_not_null_raw = hints.get("set_not_null")
    if isinstance(set_not_null_raw, list):
        for item in cast(list[Any], type_changes_raw):
            if not isinstance(item, dict):
                continue
            entry = cast(dict[str, Any], item)
            column_name = str(entry.get("column", "")).strip()
            pre_sql = str(entry.get("pre_sql", "")).strip()
            if column_name and pre_sql:
                parsed.pre_not_null_sql[column_name.casefold()] = pre_sql

    return parsed


# Constants
CDC_METADATA_COLUMNS: list[dict[str, str | bool]] = [
    {"name": "__sync_timestamp", "type": "TIMESTAMP", "nullable": False, "default": "CURRENT_TIMESTAMP"},
    {"name": "__source", "type": "VARCHAR(255)", "nullable": True},
    {"name": "__source_db", "type": "VARCHAR(255)", "nullable": True},
    {"name": "__source_table", "type": "VARCHAR(255)", "nullable": True},
    {"name": "__source_ts_ms", "type": "BIGINT", "nullable": True},
    {"name": "__cdc_operation", "type": "VARCHAR(10)", "nullable": True},
]