"""Rendering and write orchestration helpers for migration generation."""

from __future__ import annotations

from typing import Any

from jinja2 import Environment

from .data_structures import GenerationResult, MigrationColumn, RenderContext, TableMigration
from .file_writers import write_migration_file
from .manual_migrations import (
    detect_destructive_changes,
    extract_manual_migration_hints,
    write_manual_required_file,
)

_NATIVE_METADATA_COLUMN_NAMES = {
    "__sync_timestamp",
    "__source",
    "__source_db",
    "__source_table",
    "__source_start_lsn",
    "__source_seqval",
    "__cdc_operation",
}


def _render_template(
    jinja_env: Environment,
    template_name: str,
    context: dict[str, Any],
) -> str:
    """Render a Jinja2 template with the given context."""
    template = jinja_env.get_template(template_name)
    return template.render(context)


def _build_column_names_sql(columns: list[MigrationColumn]) -> str:
    """Build a comma-separated quoted column name list for INSERT/SELECT."""
    return ", ".join(f'"{column.name}"' for column in columns)


def _quote_ident(name: str) -> str:
    """Return a safely double-quoted identifier."""
    return '"' + name.replace('"', '""') + '"'


def _dedupe_names_case_insensitive(names: list[str]) -> list[str]:
    """Return unique names preserving order with case-insensitive matching."""
    seen: set[str] = set()
    deduped: list[str] = []
    for name in names:
        key = name.casefold()
        if key in seen:
            continue
        seen.add(key)
        deduped.append(name)
    return deduped


def _build_pk_names_sql(primary_keys: list[str]) -> str:
    """Build a comma-separated quoted PK column name list."""
    unique_primary_keys = _dedupe_names_case_insensitive(primary_keys)
    return ", ".join(f'"{pk}"' for pk in unique_primary_keys)


def _build_column_defs_sql(columns: list[MigrationColumn]) -> list[str]:
    """Build formatted column definitions for CREATE TABLE."""
    lines: list[str] = []
    for col in columns:
        parts = [f'    "{col.name}"', col.type]
        if not col.nullable:
            parts.append("NOT NULL")
        if col.default:
            parts.append(f"DEFAULT {col.default}")
        lines.append(" ".join(parts))
    return lines


def _build_create_table_sql(
    target_schema: str,
    table_name: str,
    columns: list[MigrationColumn],
    primary_keys: list[str],
    source_schema: str,
    generated_at: str,
    source_table_name: str | None = None,
) -> str:
    """Build a complete CREATE TABLE DDL statement."""
    col_lines = _build_column_defs_sql(columns)
    unique_primary_keys = _dedupe_names_case_insensitive(primary_keys)
    if unique_primary_keys:
        pk_expr = ", ".join(f'"{pk}"' for pk in unique_primary_keys)
        col_lines.append(f"    PRIMARY KEY ({pk_expr})")

    columns_sql = ",\n".join(col_lines)
    qualified = f'"{target_schema}"."{table_name}"'

    header = (
        "-- ============================================================================\n"
        "-- DO NOT EDIT — AUTO-GENERATED by: cdc manage-migrations generate\n"
        + f"-- Generated: {generated_at}\n"
        + f"-- Source: MSSQL [{source_schema}].[{source_table_name or table_name}]\n"
        + f"-- Target: {qualified}\n"
        + "-- ============================================================================\n"
    )

    evolution_lines: list[str] = []
    for col in columns:
        col_parts = [f'ALTER TABLE {qualified} ADD COLUMN IF NOT EXISTS "{col.name}" {col.type}']
        if col.default:
            col_parts.append(f"DEFAULT {col.default}")
        evolution_lines.append(" ".join(col_parts) + ";")
    evolution_sql = "\n".join(evolution_lines)

    return (
        header
        + "\n"
        + f"CREATE TABLE IF NOT EXISTS {qualified} (\n"
        + columns_sql
        + "\n"
        + ");\n\n"
        + "-- Schema evolution (additive only): add missing columns to existing tables.\n"
        + "-- Drift guard runs in 'cdc manage-migrations apply' (Python pre-check), not in SQL body.\n"
        + "-- Manual migration is required for remove/rename/type-change or nullability/default transitions.\n"
        + evolution_sql
        + "\n\n"
        + "-- Index on sync timestamp for efficient querying\n"
        + f'CREATE INDEX IF NOT EXISTS "idx_{table_name}_sync_ts"\n'
        + f'    ON {qualified} ("__sync_timestamp");\n'
    )


def generate_infrastructure(
    ctx: RenderContext,
    schemas: list[str],
    pattern: str,
    result: GenerationResult,
) -> None:
    """Generate infrastructure migration files (schemas, cdc-management)."""
    infra_dir = ctx.output_dir / "00-infrastructure"

    schema_sql = _render_template(
        ctx.jinja_env,
        "create-schemas.sql.j2",
        {
            "generated_at": ctx.generated_at,
            "pattern": pattern,
            "schemas": schemas,
            "sink_target": ctx.sink_target,
        },
    )
    write_migration_file(infra_dir / "01-create-schemas.sql", schema_sql, result)

    # Native mode skips legacy broker management SQL (02-cdc-management.sql).
    # Only brokered mode needs Kafka/Bento/Redpanda control tables and merge helpers.
    if ctx.runtime_mode != "native":
        mgmt_sql = _render_template(
            ctx.jinja_env,
            "cdc-management.sql.j2",
            {
                "generated_at": ctx.generated_at,
                "db_user": ctx.db_user,
                "sink_target": ctx.sink_target,
                "pattern": pattern,
            },
        )
        write_migration_file(infra_dir / "02-cdc-management.sql", mgmt_sql, result)

    if ctx.runtime_mode == "native":
        native_runtime_sql = _render_template(
            ctx.jinja_env,
            "native-cdc-runtime.sql.j2",
            {
                "generated_at": ctx.generated_at,
                "db_user": ctx.db_user,
                "sink_target": ctx.sink_target,
            },
        )
        write_migration_file(
            infra_dir / "03-native-cdc-runtime.sql",
            native_runtime_sql,
            result,
        )


def generate_table_files(
    ctx: RenderContext,
    migration: TableMigration,
    sink_table_cfg: dict[str, Any],
    result: GenerationResult,
) -> None:
    """Generate table DDL and staging/merge files for a single table."""
    tables_dir = ctx.output_dir / "01-tables"

    existing_table_sql = tables_dir / f"{migration.table_name}.sql"
    hints = extract_manual_migration_hints(sink_table_cfg)
    destructive_reasons, suggested_sql = detect_destructive_changes(
        migration.target_schema,
        migration.table_name,
        existing_table_sql,
        migration.columns,
        migration.primary_keys,
        hints,
    )
    write_manual_required_file(
        output_dir=ctx.output_dir,
        sink_name=ctx.sink_target.sink_name,
        table_name=migration.table_name,
        reasons=destructive_reasons,
        suggested_sql=suggested_sql,
        result=result,
    )

    table_sql = _build_create_table_sql(
        migration.target_schema,
        migration.table_name,
        migration.columns,
        migration.primary_keys,
        migration.source_schema,
        ctx.generated_at,
        source_table_name=migration.source_table,
    )
    write_migration_file(tables_dir / f"{migration.table_name}.sql", table_sql, result)

    if migration.primary_keys:
        unique_primary_keys = _dedupe_names_case_insensitive(migration.primary_keys)
        pk_set = {pk.casefold() for pk in unique_primary_keys}
        non_pk_cols = [c for c in migration.columns if c.name.casefold() not in pk_set]
        all_column_names = _build_column_names_sql(migration.columns)
        pk_column_names = _build_pk_names_sql(unique_primary_keys)

        update_lines: list[str] = []
        for index, col in enumerate(non_pk_cols):
            comma = "," if index < len(non_pk_cols) - 1 else ""
            update_lines.append(f'            "{col.name}" = EXCLUDED."{col.name}"{comma}')
        update_set_sql = "\n".join(update_lines)

        if ctx.runtime_mode == "native":
            staging_context = {
                "generated_at": ctx.generated_at,
                "table_name": migration.table_name,
                "source_schema_name": migration.source_schema,
                "source_table_name": migration.source_table or migration.table_name,
                "target_schema": f'"{migration.target_schema}"',
                "target_schema_raw": migration.target_schema,
                "all_column_names": all_column_names,
                "staging_insert_columns": _build_native_staging_insert_columns_sql(
                    migration.columns,
                ),
                "pull_select_sql": _build_native_pull_select_sql(migration),
                "snapshot_select_sql": _build_native_snapshot_select_sql(migration),
                "snapshot_order_by_sql": _build_snapshot_order_by_sql(
                    migration.primary_keys,
                ),
                "pk_column_names": pk_column_names,
                "delete_join_sql": _build_join_conditions_sql(
                    "target_row",
                    "staged_row",
                    unique_primary_keys,
                ),
                "update_set_sql": update_set_sql,
                "foreign_table_name": (migration.foreign_table_name or f"{migration.table_name}_CT"),
                "base_foreign_table_name": (migration.base_foreign_table_name or f"{migration.table_name}_base"),
                "min_lsn_table_name": (migration.min_lsn_table_name or f"cdc_min_lsn_{migration.table_name}"),
                "capture_instance_name": (migration.capture_instance_name or f"{migration.source_schema}_{migration.table_name}"),
                "db_user": ctx.db_user,
            }
            staging_sql = _render_template(
                ctx.jinja_env,
                "native-staging.sql.j2",
                staging_context,
            )
        else:
            staging_context = {
                "generated_at": ctx.generated_at,
                "table_name": migration.table_name,
                "target_schema": f'"{migration.target_schema}"',
                "target_schema_raw": migration.target_schema,
                "all_column_names": all_column_names,
                "pk_column_names": pk_column_names,
                "update_set_sql": update_set_sql,
                "db_user": ctx.db_user,
            }
            staging_sql = _render_template(
                ctx.jinja_env,
                "staging.sql.j2",
                staging_context,
            )
        write_migration_file(
            tables_dir / f"{migration.table_name}-staging.sql",
            staging_sql,
            result,
        )
    else:
        result.warnings.append(
            f"Table {migration.table_name}: no primary key, staging/merge skipped",
        )


def build_column_defs_sql(columns: list[MigrationColumn]) -> list[str]:
    """Public wrapper around CREATE TABLE column definition generation."""
    return _build_column_defs_sql(columns)


def build_create_table_sql(
    target_schema: str,
    table_name: str,
    columns: list[MigrationColumn],
    primary_keys: list[str],
    source_schema: str,
    generated_at: str,
    source_table_name: str | None = None,
) -> str:
    """Public wrapper around CREATE TABLE SQL generation."""
    return _build_create_table_sql(
        target_schema,
        table_name,
        columns,
        primary_keys,
        source_schema,
        generated_at,
        source_table_name=source_table_name,
    )


def _build_native_staging_insert_columns_sql(
    columns: list[MigrationColumn],
) -> str:
    """Build the INSERT column list for native staging loads."""
    final_column_names = _build_column_names_sql(columns)
    return '"batch_id", "source_instance_key", ' + final_column_names


def _build_native_pull_select_sql(migration: TableMigration) -> str:
    """Build the SELECT list used by the native FDW pull function."""
    source_table_name = migration.source_table or migration.table_name
    source_table_literal = f"'{migration.source_schema}.{source_table_name}'"
    select_lines: list[str] = []
    for column in migration.columns:
        column_name = column.name
        normalized_name = column_name.casefold()
        if normalized_name == "customer_id":
            expression = "$3::uuid"
        elif column_name == "__sync_timestamp":
            expression = "clock_timestamp()"
        elif column_name == "__source":
            expression = "'mssql_cdc'"
        elif column_name == "__source_db":
            expression = "$4"
        elif column_name == "__source_table":
            expression = source_table_literal
        elif column_name == "__source_start_lsn":
            expression = 'f."__$start_lsn"'
        elif column_name == "__source_seqval":
            expression = 'f."__$seqval"'
        elif column_name == "__cdc_operation":
            expression = 'f."__$operation"'
        else:
            expression = f"f.{_quote_ident(column_name)}"
        select_lines.append(f"            {expression}")
    return ",\n".join(select_lines)


def _build_native_snapshot_select_sql(migration: TableMigration) -> str:
    """Build the SELECT list used by the native bootstrap snapshot function."""
    source_table_name = migration.source_table or migration.table_name
    source_table_literal = f"'{migration.source_schema}.{source_table_name}'"
    select_lines: list[str] = []
    for column in migration.columns:
        column_name = column.name
        normalized_name = column_name.casefold()
        if normalized_name == "customer_id":
            expression = "$1::uuid"
        elif column_name == "__sync_timestamp":
            expression = "clock_timestamp()"
        elif column_name == "__source":
            expression = "'mssql_snapshot'"
        elif column_name == "__source_db":
            expression = "$2"
        elif column_name == "__source_table":
            expression = source_table_literal
        elif column_name == "__source_start_lsn":
            expression = "$3::bytea"
        elif column_name == "__source_seqval":
            expression = "$4::bytea"
        elif column_name == "__cdc_operation":
            expression = "2"
        else:
            expression = f"f.{_quote_ident(column_name)}"
        select_lines.append(f"            {expression}")
    return ",\n".join(select_lines)


def _build_join_conditions_sql(
    left_alias: str,
    right_alias: str,
    primary_keys: list[str],
) -> str:
    """Build equality joins on the effective primary key columns."""
    return "\n      AND ".join(
        f"{left_alias}.{_quote_ident(primary_key)} = {right_alias}.{_quote_ident(primary_key)}" for primary_key in primary_keys
    )


def _build_snapshot_order_by_sql(primary_keys: list[str]) -> str:
    """Build a deterministic ORDER BY for base-table snapshot loads."""
    source_primary_keys = [primary_key for primary_key in _dedupe_names_case_insensitive(primary_keys) if primary_key.casefold() != "customer_id"]
    return ", ".join(f"f.{_quote_ident(primary_key)}" for primary_key in source_primary_keys)
