"""Rendering and write orchestration helpers for migration generation."""

from __future__ import annotations

from typing import Any

from jinja2 import Environment

from .data_structures import GenerationResult, MigrationColumn, RenderContext, TableMigration
from .file_writers import write_migration_file
from .manual_migrations import (
    detect_destructive_changes,
    extract_manual_migration_hints,
    write_manual_required_file,
)


def _render_template(
    jinja_env: Environment,
    template_name: str,
    context: dict[str, Any],
) -> str:
    """Render a Jinja2 template with the given context."""
    template = jinja_env.get_template(template_name)
    return template.render(context)


def _build_column_names_sql(columns: list[MigrationColumn]) -> str:
    """Build a comma-separated quoted column name list for INSERT/SELECT."""
    return ", ".join(f'"{column.name}"' for column in columns)


def _dedupe_names_case_insensitive(names: list[str]) -> list[str]:
    """Return unique names preserving order with case-insensitive matching."""
    seen: set[str] = set()
    deduped: list[str] = []
    for name in names:
        key = name.casefold()
        if key in seen:
            continue
        seen.add(key)
        deduped.append(name)
    return deduped


def _build_pk_names_sql(primary_keys: list[str]) -> str:
    """Build a comma-separated quoted PK column name list."""
    unique_primary_keys = _dedupe_names_case_insensitive(primary_keys)
    return ", ".join(f'"{pk}"' for pk in unique_primary_keys)


def _build_column_defs_sql(columns: list[MigrationColumn]) -> list[str]:
    """Build formatted column definitions for CREATE TABLE."""
    lines: list[str] = []
    for col in columns:
        parts = [f'    "{col.name}"', col.type]
        if not col.nullable:
            parts.append("NOT NULL")
        if col.default:
            parts.append(f"DEFAULT {col.default}")
        lines.append(" ".join(parts))
    return lines


def _build_create_table_sql(
    target_schema: str,
    table_name: str,
    columns: list[MigrationColumn],
    primary_keys: list[str],
    source_schema: str,
    generated_at: str,
) -> str:
    """Build a complete CREATE TABLE DDL statement."""
    col_lines = _build_column_defs_sql(columns)
    unique_primary_keys = _dedupe_names_case_insensitive(primary_keys)
    if unique_primary_keys:
        pk_expr = ", ".join(f'"{pk}"' for pk in unique_primary_keys)
        col_lines.append(f"    PRIMARY KEY ({pk_expr})")

    columns_sql = ",\n".join(col_lines)
    qualified = f'"{target_schema}"."{table_name}"'

    header = (
        "-- ============================================================================\n"
        "-- DO NOT EDIT — AUTO-GENERATED by: cdc manage-migrations generate\n"
        + f"-- Generated: {generated_at}\n"
        + f"-- Source: MSSQL [{source_schema}].[{table_name}]\n"
        + f"-- Target: {qualified}\n"
        + "-- ============================================================================\n"
    )

    evolution_lines: list[str] = []
    for col in columns:
        col_parts = [f'ALTER TABLE {qualified} ADD COLUMN IF NOT EXISTS "{col.name}" {col.type}']
        if col.default:
            col_parts.append(f"DEFAULT {col.default}")
        evolution_lines.append(" ".join(col_parts) + ";")
    evolution_sql = "\n".join(evolution_lines)

    return (
        header + "\n"
        + f'CREATE TABLE IF NOT EXISTS {qualified} (\n'
        + columns_sql + "\n"
        + ");\n\n"
        + "-- Schema evolution (additive only): add missing columns to existing tables.\n"
        + "-- Drift guard runs in 'cdc manage-migrations apply' (Python pre-check), not in SQL body.\n"
        + "-- Manual migration is required for remove/rename/type-change or nullability/default transitions.\n"
        + evolution_sql + "\n\n"
        + "-- Index on sync timestamp for efficient querying\n"
        + f'CREATE INDEX IF NOT EXISTS "idx_{table_name}_sync_ts"\n'
        + f'    ON {qualified} ("__sync_timestamp");\n'
    )


def generate_infrastructure(
    ctx: RenderContext,
    schemas: list[str],
    pattern: str,
    result: GenerationResult,
) -> None:
    """Generate infrastructure migration files (schemas, cdc-management)."""
    infra_dir = ctx.output_dir / "00-infrastructure"

    schema_sql = _render_template(
        ctx.jinja_env,
        "create-schemas.sql.j2",
        {
            "generated_at": ctx.generated_at,
            "pattern": pattern,
            "schemas": schemas,
            "sink_target": ctx.sink_target,
        },
    )
    write_migration_file(infra_dir / "01-create-schemas.sql", schema_sql, result)

    mgmt_sql = _render_template(
        ctx.jinja_env,
        "cdc-management.sql.j2",
        {
            "generated_at": ctx.generated_at,
            "db_user": ctx.db_user,
            "sink_target": ctx.sink_target,
            "pattern": pattern,
        },
    )
    write_migration_file(infra_dir / "02-cdc-management.sql", mgmt_sql, result)


def generate_table_files(
    ctx: RenderContext,
    migration: TableMigration,
    sink_table_cfg: dict[str, Any],
    result: GenerationResult,
) -> None:
    """Generate table DDL and staging/merge files for a single table."""
    tables_dir = ctx.output_dir / "01-tables"

    existing_table_sql = tables_dir / f"{migration.table_name}.sql"
    hints = extract_manual_migration_hints(sink_table_cfg)
    destructive_reasons, suggested_sql = detect_destructive_changes(
        migration.target_schema,
        migration.table_name,
        existing_table_sql,
        migration.columns,
        migration.primary_keys,
        hints,
    )
    write_manual_required_file(
        output_dir=ctx.output_dir,
        sink_name=ctx.sink_target.sink_name,
        table_name=migration.table_name,
        reasons=destructive_reasons,
        suggested_sql=suggested_sql,
        result=result,
    )

    table_sql = _build_create_table_sql(
        migration.target_schema,
        migration.table_name,
        migration.columns,
        migration.primary_keys,
        migration.source_schema,
        ctx.generated_at,
    )
    write_migration_file(tables_dir / f"{migration.table_name}.sql", table_sql, result)

    if migration.primary_keys:
        unique_primary_keys = _dedupe_names_case_insensitive(migration.primary_keys)
        pk_set = {pk.casefold() for pk in unique_primary_keys}
        non_pk_cols = [c for c in migration.columns if c.name.casefold() not in pk_set]
        all_column_names = _build_column_names_sql(migration.columns)
        pk_column_names = _build_pk_names_sql(unique_primary_keys)

        update_lines: list[str] = []
        for index, col in enumerate(non_pk_cols):
            comma = "," if index < len(non_pk_cols) - 1 else ""
            update_lines.append(f'            "{col.name}" = EXCLUDED."{col.name}"{comma}')
        update_set_sql = "\n".join(update_lines)

        staging_context = {
            "generated_at": ctx.generated_at,
            "table_name": migration.table_name,
            "target_schema": f'"{migration.target_schema}"',
            "target_schema_raw": migration.target_schema,
            "all_column_names": all_column_names,
            "pk_column_names": pk_column_names,
            "update_set_sql": update_set_sql,
            "db_user": ctx.db_user,
        }
        staging_sql = _render_template(ctx.jinja_env, "staging.sql.j2", staging_context)
        write_migration_file(
            tables_dir / f"{migration.table_name}-staging.sql",
            staging_sql,
            result,
        )
    else:
        result.warnings.append(
            f"Table {migration.table_name}: no primary key, staging/merge skipped",
        )


def build_column_defs_sql(columns: list[MigrationColumn]) -> list[str]:
    """Public wrapper around CREATE TABLE column definition generation."""
    return _build_column_defs_sql(columns)


def build_create_table_sql(
    target_schema: str,
    table_name: str,
    columns: list[MigrationColumn],
    primary_keys: list[str],
    source_schema: str,
    generated_at: str,
) -> str:
    """Public wrapper around CREATE TABLE SQL generation."""
    return _build_create_table_sql(
        target_schema,
        table_name,
        columns,
        primary_keys,
        source_schema,
        generated_at,
    )
