"""Migration SQL generator for CDC pipelines.

Generates PostgreSQL migration files from service config and table definitions.
Organises output per sink target from the service config:
    migrations/
    └── {sink_name}/                 (e.g., sink_asma.directory/)
        ├── 00-infrastructure/
        │   ├── 01-create-schemas.sql
        │   └── 02-cdc-management.sql
        ├── 01-tables/
        │   ├── Actor.sql
        │   ├── Actor-staging.sql
        │   └── ...per table
        └── manifest.yaml

Uses Jinja2 templates from cdc_generator/templates/migrations/.

Example:
    >>> from cdc_generator.core.migration_generator import generate_migrations
    >>> result = generate_migrations("adopus")
    >>> print(result.files_written)
    12
"""

from __future__ import annotations

import os
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from jinja2 import Environment, FileSystemLoader

from cdc_generator.helpers.helpers_logging import (
    print_error,
    print_header,
    print_info,
    print_success,
    print_warning,
)
from cdc_generator.helpers.service_config import (
    get_project_root,
    load_service_config,
)
from cdc_generator.helpers.type_mapper import TypeMapper

from .migration_generator.columns import (
    build_columns_from_table_def as _build_columns_from_table_def,
)
from .migration_generator.columns import (
    build_full_column_list as _build_full_column_list,
)
from .migration_generator.data_structures import (
    GenerationResult,
    RenderContext,
    ServiceData,
)
from .migration_generator.file_writers import write_manifest as _write_manifest
from .migration_generator.manual_migrations import (
    detect_removed_tables_for_manual_files as _detect_removed_tables_for_manual_files,
)
from .migration_generator.rendering import (
    generate_infrastructure as _generate_infrastructure,
)
from .migration_generator.rendering import (
    generate_table_files as _generate_table_files,
)
from .migration_generator.service_parsing import (
    derive_target_schemas as _derive_target_schemas,
)
from .migration_generator.service_parsing import (
    get_sinks,
    resolve_sink_target,
)
from .migration_generator.service_parsing import (
    resolve_pattern as _resolve_pattern,
)
from .migration_generator.service_parsing import (
    validate_db_shared_customer_id as _validate_db_shared_customer_id,
)
from .migration_generator.table_loading import load_table_definitions
from .migration_generator.table_processing import process_table as _process_table

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

TEMPLATES_DIR = Path(__file__).parent.parent / "templates" / "migrations"
DO_NOT_EDIT_HEADER = "-- DO NOT EDIT — AUTO-GENERATED by: cdc manage-migrations generate"

DEFAULT_DB_USER = "postgres"

# ---------------------------------------------------------------------------


def _create_jinja_env() -> Environment:
    """Create Jinja2 environment with custom filters.

    Returns:
        Configured Jinja2 Environment.
    """
    env = Environment(
        loader=FileSystemLoader(str(TEMPLATES_DIR)),
        keep_trailing_newline=True,
        trim_blocks=True,
        lstrip_blocks=True,
    )
    env.filters["format_pk"] = lambda name: f'"{name}"'
    return env


def build_columns_from_table_def(
    table_def: dict[str, Any],
    ignore_columns: list[str] | None = None,
    type_mapper: TypeMapper | None = None,
) -> tuple[list[Any], list[str]]:
    """Compatibility wrapper for column extraction helper."""
    return _build_columns_from_table_def(table_def, ignore_columns, type_mapper)


def build_full_column_list(
    table_def: dict[str, Any],
    sink_cfg: dict[str, object],
    service_config: dict[str, object],
    source_key: str,
    type_mapper: TypeMapper | None = None,
) -> tuple[list[Any], list[str]]:
    """Compatibility wrapper for full column-list builder."""
    return _build_full_column_list(
        table_def,
        sink_cfg,
        service_config,
        source_key,
        type_mapper,
    )


# ---------------------------------------------------------------------------
# Main entry point
# ---------------------------------------------------------------------------


def generate_migrations(
    service_name: str = "adopus",
    *,
    table_filter: str | None = None,
    dry_run: bool = False,
    output_dir: Path | None = None,
) -> GenerationResult:
    """Generate PostgreSQL migration files for a CDC service.

    Reads service config, table definitions, and source-groups to produce
    a complete set of idempotent migration SQL files.

    Args:
        service_name: Service name to generate migrations for.
        table_filter: Optional table name filter (only generate for this table).
        dry_run: If True, print what would be generated without writing files.
        output_dir: Override output directory (default: migrations/).

    Returns:
        GenerationResult with file counts and any errors/warnings.

    Example:
        >>> result = generate_migrations("adopus")
        >>> print(f"Generated {result.files_written} files for {result.tables_processed} tables")
    """
    result = GenerationResult()
    project_root = get_project_root()
    generated_at = datetime.now(tz=UTC).strftime("%Y-%m-%d %H:%M:%S UTC")
    db_user = os.environ.get("CDC_DB_USER", DEFAULT_DB_USER)

    # Resolve output directory
    if output_dir is None:
        output_dir = project_root / "migrations"
    result.output_dir = output_dir

    print_header(f"Generating migrations for service: {service_name}")

    # 1. Load service config
    try:
        service_config = load_service_config(service_name)
    except FileNotFoundError as e:
        result.errors.append(str(e))
        print_error(str(e))
        return result

    # 2. Load table definitions from services/_schemas/
    table_defs = load_table_definitions(service_name, project_root)
    if not table_defs:
        result.warnings.append(
            f"No table definitions found in services/_schemas/{service_name}/. "
            + "Run 'cdc manage-services config --inspect' first to generate them.",
        )

    # 3. Initialize type mapper (MSSQL → PostgreSQL)
    try:
        type_mapper: TypeMapper | None = TypeMapper("mssql", "pgsql")
    except FileNotFoundError:
        type_mapper = None
        result.warnings.append(
            "No MSSQL→PG type mapping file found. Column types will not be converted.",
        )
        print_warning(result.warnings[-1])

    # 4. Get sinks organized per sink target
    sinks = get_sinks(service_config)
    if not sinks:
        result.errors.append("No sink tables found in service config")
        print_error(result.errors[-1])
        return result

    # 5. Resolve pattern and create shared service data
    pattern = _resolve_pattern(project_root)
    jinja_env = _create_jinja_env()
    svc_data = ServiceData(
        service_config=service_config,
        table_defs=table_defs,
        type_mapper=type_mapper,
    )

    # 5b. db-shared validation: warn if customer_id missing from tables
    if pattern == "db-shared":
        _validate_db_shared_customer_id(sinks, result)

    # 6. Process each sink target separately
    for sink_name, sink_tables_iter in sorted(sinks.items()):
        tables_for_sink = sink_tables_iter

        # Apply table filter
        if table_filter:
            filter_lower = table_filter.casefold()
            tables_for_sink = {
                k: v for k, v in tables_for_sink.items()
                if filter_lower in k.casefold()
            }
            if not tables_for_sink:
                continue

        # Resolve sink target (database names from sink-groups.yaml)
        sink_target = resolve_sink_target(sink_name, project_root)
        result.sink_targets.append(sink_target)
        schemas = _derive_target_schemas(tables_for_sink)
        result.schemas = sorted(set(result.schemas) | set(schemas))

        ctx = RenderContext(
            jinja_env=jinja_env,
            output_dir=output_dir / sink_name,
            generated_at=generated_at,
            db_user=db_user,
            sink_target=sink_target,
        )

        _generate_for_sink(
            ctx=ctx,
            sink_tables=tables_for_sink,
            schemas=schemas,
            pattern=pattern,
            svc_data=svc_data,
            result=result,
            dry_run=dry_run,
        )

    if dry_run:
        return result

    # Summary
    sink_count = len(result.sink_targets)
    print_success(
        f"Generated {result.files_written} files for {result.tables_processed} tables"
        + f" ({len(result.schemas)} schemas, {sink_count} sink{'s' if sink_count != 1 else ''})",
    )
    if result.warnings:
        for w in result.warnings:
            print_warning(w)
    if result.errors:
        for e in result.errors:
            print_error(e)

    return result


# ---------------------------------------------------------------------------
# Per-sink generation
# ---------------------------------------------------------------------------


def _generate_for_sink(
    *,
    ctx: RenderContext,
    sink_tables: dict[str, dict[str, Any]],
    schemas: list[str],
    pattern: str,
    svc_data: ServiceData,
    result: GenerationResult,
    dry_run: bool,
) -> None:
    """Generate all migration files for a single sink target.

    Args:
        ctx: Shared render context (includes output_dir and sink_target).
        sink_tables: Tables for this sink.
        schemas: Target schemas to create.
        pattern: Architecture pattern.
        svc_data: Loaded service data (config, table defs, type mapper).
        result: GenerationResult to update.
        dry_run: If True, only print what would be generated.
    """
    if dry_run:
        db_list = ", ".join(
            f"{e}={d}" for e, d in sorted(ctx.sink_target.databases.items())
        )
        print_info(f"[DRY RUN] Sink: {ctx.sink_target.sink_name}")
        print_info(f"  Output: {ctx.output_dir}")
        print_info(f"  Databases: {db_list or '(none resolved)'}")
        print_info(f"  Pattern: {pattern}")
        print_info(f"  Schemas: {len(schemas)}")
        print_info(f"  Tables: {len(sink_tables)}")
        for table_key in sorted(sink_tables):
            print_info(f"    - {table_key}")
        return

    # Generate infrastructure files
    _generate_infrastructure(ctx, schemas, pattern, result)

    _detect_removed_tables_for_manual_files(
        output_dir=ctx.output_dir,
        sink_name=ctx.sink_target.sink_name,
        sink_tables=sink_tables,
        result=result,
    )

    # Generate per-table files
    tables_generated: list[str] = []
    for sink_key in sorted(sink_tables):
        sink_cfg = sink_tables[sink_key]
        migration = _process_table(
            sink_key, sink_cfg, svc_data.service_config,
            svc_data.table_defs, result, svc_data.type_mapper,
        )
        if migration is None:
            continue

        _generate_table_files(ctx, migration, sink_cfg, result)
        tables_generated.append(migration.table_name)
        result.tables_processed += 1

    # Write per-sink manifest
    manifest_written = _write_manifest(
        ctx.output_dir, tables_generated, schemas, ctx.generated_at, ctx.sink_target,
    )
    _ = manifest_written
    result.files_written += 1


